$(document).ready(function(){
	console.log("Ready...");
	var cities = [
			"atlanta",
			"austin",
			"boston",
			"chicago",
			"dallas",
			"denver",
			"detroit",
			"houston",
			"lasvegas",
			"losangeles",
			"miami",
			"minneapolis",
			"newyork",
			"orangecounty",
			"philadelphia",
			"phoenix",
			"portland",
			"raleigh",
			"sacramento",
			"sandiego",
			"seattle",
			"sfbay",
			"washingtondc"
		]
	for(int i=0;i<cities.length;i++){
		console.log(cities[i]);
	}
});